In [2]:
#Reduction is an operation performend on tensor which leaves tensor with one less dimension.

import tensorflow as tf
sess=tf.InteractiveSession()
x=tf.constant([[1,2,3],
              [2,3,1],
              [-1,-3,-2]])
boolean_tensor=tf.constant([[True,False,True],
                           [False,False,True],
                           [True,False,False]])

In [5]:
# 'tf.reduce_prod': Computes the "Product" of elements across dimensions of a tensor.
tf.reduce_prod(x,reduction_indices=1).eval()

array([ 6,  6, -6], dtype=int32)

In [7]:
# 'tf.reduce_min': Computes the "minimum" of elements across dimensions of a tensor.
tf.reduce_min(x,reduction_indices=1).eval()

array([ 1,  1, -3], dtype=int32)

In [8]:
# 'tf.reduce_max': Computes the "maximum" of elements across dimensions of a tensor.
tf.reduce_min(x,reduction_indices=1).eval()

array([ 1,  1, -3], dtype=int32)

In [9]:
# 'tf.reduce_mean': Computes the "mean" of elements across dimensions of a tensor.
tf.reduce_mean(x,reduction_indices=1).eval()

array([ 2,  2, -2], dtype=int32)

In [12]:
# 'tf.reduce_all': Computes the "logical AND" of elements across dimensions of a tensor.
tf.reduce_all(boolean_tensor,reduction_indices=1).eval()

array([False, False, False], dtype=bool)

In [13]:
# 'tf.reduce_all': Computes the "logical OR" of elements across dimensions of a tensor.
tf.reduce_any(boolean_tensor,reduction_indices=1).eval()

array([ True,  True,  True], dtype=bool)