In [1]:
import tensorflow as tf
sess=tf.InteractiveSession()

In [4]:
x=tf.constant([[2,5,3,-5],
              [0,3,-2,5],
              [4,3,5,3],
              [6,1,4,0],
              [6,1,4,0]])
seg_ids=tf.constant([0,1,1,2,2]);

In [5]:
#'tf.segment_sum' : Computes the sum along segments of a tensor.
tf.segment_sum(x,seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  6,  3,  8],
       [12,  2,  8,  0]], dtype=int32)

In [6]:
#'tf.segment_prof' : Computes the prod along segments of a tensor.
tf.segment_prod(x,seg_ids).eval()

array([[  2,   5,   3,  -5],
       [  0,   9, -10,  15],
       [ 36,   1,  16,   0]], dtype=int32)

In [7]:
#'tf.segment_min' : This gives minimum value to the group
tf.segment_min(x,seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  3],
       [ 6,  1,  4,  0]], dtype=int32)

In [8]:
#'tf.segment_min' : This gives maximum value to the group
tf.segment_max(x,seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  3,  5,  5],
       [ 6,  1,  4,  0]], dtype=int32)

In [9]:
#'tf.segment_mean' : This gives mean value to the group
tf.segment_mean(x,seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 2,  3,  1,  4],
       [ 6,  1,  4,  0]], dtype=int32)