In [1]:
import tensorflow as tf
sess=tf.InteractiveSession()

In [3]:
x=tf.constant([[2,5,3,-5],[0,3,2,5],[4,3,5,3],[6,1,4,0]])
listx=tf.constant([1,2,3,4,5,6,7,8])
listy=tf.constant([4,5,8,9])
boolx=tf.constant([[True,False],[False,True]])


In [4]:
# Returns the index with the minimum value across axes of a tensor.
tf.argmin(x,1).eval()

array([3, 0, 1, 3])

In [5]:
# Returns the index with the maximum value across axes of a tensor.
tf.argmax(x,1).eval()

array([1, 3, 2, 0])

In [8]:
#Returens difference between 2 lists
tf.setdiff1d(listx,listy)[0].eval()

array([1, 2, 3, 6, 7], dtype=int32)

In [9]:
#Returns true values
tf.where(boolx).eval()

array([[0, 0],
       [1, 1]])

In [10]:
#Returns Unique values in a list
tf.unique(listx)[0].eval()

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)