In [1]:
import tensorflow as tf
sess=tf.InteractiveSession()

In [3]:
x=tf.constant([[2,5,3,-5],
               [0,3,2,5],
               [4,3,5,3],
               [6,1,4,0]])
tf.shape(x).eval()

array([4, 4], dtype=int32)

In [4]:
tf.size(x).eval()

16

In [5]:
tf.rank(x).eval()

2

In [6]:
tf.reshape(x,[8,2]).eval()

array([[ 2,  5],
       [ 3, -5],
       [ 0,  3],
       [ 2,  5],
       [ 4,  3],
       [ 5,  3],
       [ 6,  1],
       [ 4,  0]], dtype=int32)

In [7]:
tf.squeeze(x).eval()

array([[ 2,  5,  3, -5],
       [ 0,  3,  2,  5],
       [ 4,  3,  5,  3],
       [ 6,  1,  4,  0]], dtype=int32)

In [8]:
tf.expand_dims(x,1).eval()

array([[[ 2,  5,  3, -5]],

       [[ 0,  3,  2,  5]],

       [[ 4,  3,  5,  3]],

       [[ 6,  1,  4,  0]]], dtype=int32)