In [1]:
import tensorflow as tf
sess=tf.InteractiveSession()

In [4]:
t_matrix=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
t_array = tf.constant([1,2,3,4,9,8,7,6])
t_array2=tf.constant([2,3,4,5,6,7,8,9])
tf.slice(t_matrix,[1,1],[2,2]).eval()

array([[5, 6],
       [8, 9]], dtype=int32)

In [5]:
#This will split the array into 2
tf.split(axis=0,num_or_size_splits=2,value=t_array)

[<tf.Tensor 'split:0' shape=(4,) dtype=int32>,
 <tf.Tensor 'split:1' shape=(4,) dtype=int32>]

In [7]:
# We can tile a tensor 5 times using:
tf.tile([1,2],[5]).eval()

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2], dtype=int32)

In [13]:
# 2D matrix padding: tf.pad(matrix,[Top_padding,Bottom_padding],[Left_Padding,Right_Padding], mode='CONSTANT',name=None)
tf.pad(t_matrix,[[0,2],[2,1]]).eval()

array([[0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [15]:
#Concatenate two tensors
tf.concat(axis=0,values=[t_array,t_array2]).eval()

array([1, 2, 3, 4, 9, 8, 7, 6, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [16]:
#Stack two tensors
tf.stack([t_array,t_array2]).eval()

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [17]:
sess.run(tf.unstack(t_matrix))

[array([1, 2, 3], dtype=int32),
 array([4, 5, 6], dtype=int32),
 array([7, 8, 9], dtype=int32)]

In [18]:
tf.reverse(t_matrix,[False,True]).eval()

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]], dtype=int32)